# Site settings
title: Finn Boire
email: finn.boire@gmail.com
description: The world's pretty cool!
url: "https://steampunc.github.io"
twitter_username: steampunc
github_username: steampunc 
paginate: 10

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
